database:
  product:
    adapter: mysql
    host: 127.0.0.1
    port: 3306
  news:
    mysql:
      host: 192.168.10.101
      port: 3306
      username: root
      password: P@ssw0rd
      dbname: news-db
      adapter: mysql
